development:
  adapter: postgresql
  encoding: unicode
  database: expense_report_development
  pool: 5
  username: postgres
  password: hmhsr0

test:
  adapter: postgresql
  encoding: unicode
  database: expense_report_test
  pool: 5
  username: postgres
  password: hmhsr0
  
production:
  adapter: postgresql
  encoding: unicode
  database: expense_report_production
  pool: 5
  username: postgres
  password: hmhsr0