require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExpenseAttachmentsController do

  # This should return the minimal set of attributes required to create a valid
  # ExpenseAttachment. As you add validations to ExpenseAttachment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExpenseAttachmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all expense_attachments as @expense_attachments" do
      expense_attachment = ExpenseAttachment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:expense_attachments).should eq([expense_attachment])
    end
  end

  describe "GET show" do
    it "assigns the requested expense_attachment as @expense_attachment" do
      expense_attachment = ExpenseAttachment.create! valid_attributes
      get :show, {:id => expense_attachment.to_param}, valid_session
      assigns(:expense_attachment).should eq(expense_attachment)
    end
  end

  describe "GET new" do
    it "assigns a new expense_attachment as @expense_attachment" do
      get :new, {}, valid_session
      assigns(:expense_attachment).should be_a_new(ExpenseAttachment)
    end
  end

  describe "GET edit" do
    it "assigns the requested expense_attachment as @expense_attachment" do
      expense_attachment = ExpenseAttachment.create! valid_attributes
      get :edit, {:id => expense_attachment.to_param}, valid_session
      assigns(:expense_attachment).should eq(expense_attachment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExpenseAttachment" do
        expect {
          post :create, {:expense_attachment => valid_attributes}, valid_session
        }.to change(ExpenseAttachment, :count).by(1)
      end

      it "assigns a newly created expense_attachment as @expense_attachment" do
        post :create, {:expense_attachment => valid_attributes}, valid_session
        assigns(:expense_attachment).should be_a(ExpenseAttachment)
        assigns(:expense_attachment).should be_persisted
      end

      it "redirects to the created expense_attachment" do
        post :create, {:expense_attachment => valid_attributes}, valid_session
        response.should redirect_to(ExpenseAttachment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expense_attachment as @expense_attachment" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExpenseAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:expense_attachment => {}}, valid_session
        assigns(:expense_attachment).should be_a_new(ExpenseAttachment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExpenseAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:expense_attachment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expense_attachment" do
        expense_attachment = ExpenseAttachment.create! valid_attributes
        # Assuming there are no other expense_attachments in the database, this
        # specifies that the ExpenseAttachment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExpenseAttachment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => expense_attachment.to_param, :expense_attachment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested expense_attachment as @expense_attachment" do
        expense_attachment = ExpenseAttachment.create! valid_attributes
        put :update, {:id => expense_attachment.to_param, :expense_attachment => valid_attributes}, valid_session
        assigns(:expense_attachment).should eq(expense_attachment)
      end

      it "redirects to the expense_attachment" do
        expense_attachment = ExpenseAttachment.create! valid_attributes
        put :update, {:id => expense_attachment.to_param, :expense_attachment => valid_attributes}, valid_session
        response.should redirect_to(expense_attachment)
      end
    end

    describe "with invalid params" do
      it "assigns the expense_attachment as @expense_attachment" do
        expense_attachment = ExpenseAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExpenseAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => expense_attachment.to_param, :expense_attachment => {}}, valid_session
        assigns(:expense_attachment).should eq(expense_attachment)
      end

      it "re-renders the 'edit' template" do
        expense_attachment = ExpenseAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExpenseAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => expense_attachment.to_param, :expense_attachment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expense_attachment" do
      expense_attachment = ExpenseAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => expense_attachment.to_param}, valid_session
      }.to change(ExpenseAttachment, :count).by(-1)
    end

    it "redirects to the expense_attachments list" do
      expense_attachment = ExpenseAttachment.create! valid_attributes
      delete :destroy, {:id => expense_attachment.to_param}, valid_session
      response.should redirect_to(expense_attachments_url)
    end
  end

end
